// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using examen_final_5390_18_10587.conecction;

namespace examen_final_5390_18_10587.Migrations
{
    [DbContext(typeof(Conn))]
    partial class ConnModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("examen_final_5390_18_10587.models.IngresoProductoModels", b =>
                {
                    b.Property<int>("IngresoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadProductoIngreso")
                        .HasColumnType("int");

                    b.Property<string>("EstadoProveedor")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("NombreBodegaIngreso")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombreProductoIngreso")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PrecioProductoIngreso")
                        .HasColumnType("int");

                    b.Property<string>("ProveedorProductoIngreso")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IngresoProducto");

                    b.ToTable("tbl_Ingreso_producto");
                });

            modelBuilder.Entity("examen_final_5390_18_10587.models.ProductoModels", b =>
                {
                    b.Property<int>("CodigoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadProducto")
                        .HasColumnType("int");

                    b.Property<string>("EstadoProducto")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PrecioProducto")
                        .HasColumnType("int");

                    b.Property<string>("ProveedorProducto")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("CodigoProducto");

                    b.ToTable("tbl_producto");
                });

            modelBuilder.Entity("examen_final_5390_18_10587.models.ProveedorModels", b =>
                {
                    b.Property<int>("CodigoProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DireccionProducto")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EstadoProveedor")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProveedorProducto")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Telefonoproveedor")
                        .HasColumnType("int");

                    b.HasKey("CodigoProveedor");

                    b.ToTable("tbl_proveedor");
                });
#pragma warning restore 612, 618
        }
    }
}
